### ISSUE TITLE
Getting "'Client error: 400" when using any example on the home page.

### ISSUE THREAD

**Issue by philcarbone** [Microsoft/ApplicationInsights-PHP#12]
The error comes from Guzzle. Here is a trace:
```
#0 ...\vendor\guzzlehttp\promises\src\Promise.php(201): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 ...\vendor\guzzlehttp\promises\src\Promise.php(154): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#2 ...\vendor\guzzlehttp\promises\src\TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#3 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#4 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 ...\vendor\guzzlehttp\promises\src\Promise.php(242): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 ...\vendor\guzzlehttp\promises\src\Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 ...\vendor\guzzlehttp\promises\src\Promise.php(263): GuzzleHttp\Promise\Promise->waitIfPending()
#8 ...\vendor\guzzlehttp\promises\src\Promise.php(221): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 ...\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 ...\vendor\guzzlehttp\guzzle\src\Client.php(129): GuzzleHttp\Promise\Promise->wait()
#11 ...\vendor\guzzlehttp\guzzle\src\Client.php(87): GuzzleHttp\Client->request('post', 'https://dc.serv...', Array)
#12 ...\vendor\microsoft\application-insights\ApplicationInsights\Channel\Telemetry_Channel.php(178): GuzzleHttp\Client->__call('post', Array)
#13 ...\vendor\microsoft\application-insights\ApplicationInsights\Channel\Telemetry_Channel.php(178): GuzzleHttp\Client->post('https://dc.serv...', Array)
#14 ...\vendor\microsoft\application-insights\ApplicationInsights\Telemetry_Client.php(281): ApplicationInsights\Channel\Telemetry_Channel->send()
#15  Analytics.php(58): ApplicationInsights\Telemetry_Client->flush()
```

I am using this in a class:
```
$this->telemetryClient = new \ApplicationInsights\Telemetry_Client();
$this->telemetryClient->getContext()->setInstrumentationKey(INSTRUMENTATION_KEY);
$this->telemetryClient->trackEvent('Test');
$this->telemetryClient->flush();
```

Note: INSTRUMENTATION_KEY is a constant.

**Comment by JakubOleksy** [comment]
Can you try capturing the request in Fiddler and see more details from the response?

**Comment by philcarbone** [comment]
Is there a way you get PHP or Guzzle to send all of its requests through my Fiddler proxy (globally)?

I personally have made my own cURL classes that use a global config to enable a proxy. I will scour the internet some more on this but I've looked this up in the past with no success. 

Any tips?

**Comment by philcarbone** [comment]
I found the answer. Found this on stackoverflow:

> includes code to read the environment variables to see if HTTP_PROXY and HTTPS_PROXY are set on the current machine, and if yes, Guzzle will use those values.

I'm trying it out now

**Comment by philcarbone** [comment]
After adding this in my PHP:
```
putenv("HTTP_PROXY=http://localhost:8888");
putenv("HTTPS_PROXY=http://localhost:8888");
```

I am getting this:
```
HTTP/1.1 400 Invalid instrumentation key
Content-Length: 117
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.5
x-ms-session-id: 159E04C0-71A5-416F-AB40-A46E7CD94BAA
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Name, Content-Type, Accept
Access-Control-Allow-Origin: *
X-Powered-By: ASP.NET
Date: Sat, 20 Feb 2016 16:16:33 GMT

{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Invalid instrumentation key"}]}
```

I think that is self explanatory :)   Thanks!

**Comment by JakubOleksy** [comment]
So you've got it figured out? In the code there is a line commented out that routes the requests through the fiddler proxy as well.
