### ISSUE TITLE
PHP Fatal error: 503 Service Unavailable

### ISSUE THREAD

**Issue by ArmandoTrujillo** [Microsoft/ApplicationInsights-PHP#60]
hello,

I get this error when I want to make the track Event. can anyone help me?

PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST https://dc.services.visualstudio.com/v2/track` resulted in a `500 Processing error` response:
{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":500,"message":"Processing error"}]}
' in D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 D:\home\site\wwwroot\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 D:\home\site\wwwroot\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 D:\home\site\wwwroot\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
# in D:\home\site\wwwroot\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

thanks

**Comment by jondmcelroy** [comment]
This error appears to occur randomly (from our perspective). For instance, I will go a month not seeing it and then for a couple days I will see it quite often blowing up my logs. I have to assume its just an issue on Microsofts end, as manually sending the failed items later always returns a 200.
